# Generated by Django 5.1.4 on 2025-01-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='apdated_at',
            new_name='updated_at',
        ),
    ]
